services:
  - type: web
    name: fashion-recommendation-system
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run main.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.13
